name: KitPvP
version: 1.0.0
main: me.athena222.kitpvp.Main
author: Athena222
description: A custom KitPvP plugin.
depend: [Vault]
softdepend: [FeatherBoard]

commands:
   admin:
     description: KitPvP Administration Commands.
     usage: /admin
     aliases: [kitpvpadmin]

permissions:     
   kitpvp.admin:
     description: Gives access to /admin
     default: op